---
title: "Cleaning and Wrangling Data"
author: "Clarissa Reyes"
date: "2023-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages
```{r load packages, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(readr)
```

# Introduction
This data was downloaded from [this link](https://knb.ecoinformatics.org/view/df35b.304.2) on Apr 4, 2023.

## Read data
```{r}
catch_original <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1") 
```

## Explore data

```{r, eval=FALSE, echo=FALSE}
head(catch_original)
sort(unique(catch_original$Year)) #list all unique year values and sort
unique(catch_original$Region)

```

# Clean and reshape

## Remove columns 

```{r}
#one way to select columns
catch_data <- catch_original %>% 
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)

#another way
catch_data2 <- catch_original %>% 
  select(-All, -notesRegCode)
```

## Check column types

```{r}
glimpse(catch_data2)
catch_clean <- catch_data2 %>% 
  mutate(Chinook = as.numeric(Chinook))
```

## Check NA
```{r}
i <- which(is.na(catch_clean$Chinook))
# is.na looks for NA  
# which tells you the position of NA

catch_data[i,] #check the raw data for which row 'i' is in
```

## Fix Chinook column
```{r}

catch_clean <- catch_data %>% 
  mutate(Chinook = if_else(Chinook == "I", #wherever Chinook is I
                                      "1", # if I, enter 1
                                      Chinook), # if not, don't do anything
          Chinook = as.numeric(Chinook)) # 1 was still a character previously, so this ensures numeric 
catch_clean[i,] #check that row to confirm change
```

## Reshape
From wide to long, use pivot_longer
```{r}
catch_long <- catch_clean %>% 
  pivot_longer(cols = -c(Region, Year),
               names_to = "species", #quotes used here because these cols do not exist yet
               values_to = "catch")
head(catch_long)

catch_wide <- catch_long %>% 
  pivot_wider(names_from = species,
              values_from = catch)
head(catch_wide)
```
## Rename
```{r}
catch_long <- catch_long %>% 
  rename(catch_thousands = catch)
```

## Add a column
```{r}
catch_long <- catch_long %>% 
  mutate(catch = catch_thousands*1000) %>% 
  select(-catch_thousands)
```

## Split-Apply- Workflow
```{r}
mean_region <- catch_long %>% 
  group_by(Region) %>% 
  summarise(catch_mean = mean(catch))

mean_reg_yr <- catch_long %>% 
  group_by(Region,Year) %>% 
  summarise(catch_mean = mean(catch))

n_region <- catch_long %>% 
  group_by(Region) %>% 
  summarize(obs_n=n()) #counts how many rows/observations of data per region



```

